repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0  # Update if there's a newer version
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-toml
      - id: debug-statements

  - repo: https://github.com/psf/black
    rev: 22.6.0  # Check for newer version
    hooks:
      - id: black

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0  # Check for newer version
    hooks:
      - id: isort

  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1  # Update to the latest version, e.g., 5.0.4
    hooks:
      - id: flake8
        additional_dependencies:
          - wemake-python-styleguide==0.16.1  # Update to the latest compatible version or remove temporarily
