name: opensearch_manager
channels:
    - conda-forge
    - defaults
dependencies:
  - python>=3.9,<3.10
  - pip==21.3.1
  - psycopg2==2.9.2
  - oscrypto==1.2.1
  - cryptography==3.4.8
  - click==7.1.2
  - python-dotenv==0.14.0
  - pyyaml
  - pip:
      - -r requirements.txt