version: '3'
services:
    dev-env:
        build: .
        container_name: dev-env
        volumes:
            - .:/usr/src/app
        command: [ "/bin/bash" ]
        depends_on:
            - "opensearch-node"
        ports:
            - 8888:8888
        networks:
            - opensearch-net
        tty: true
        stdin_open: true
        profiles:
            - dev-env