name: Python lints

on: [pull_request]

jobs:
  lints:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Python setup
      uses: actions/setup-python@v4
      with:
        python-version: 3.x

    - name: Pre-commit action
      uses: pre-commit/action@v3.0.0

    # - name: Pre-commit lite action
    #   uses: pre-commit-ci/lite-action@v1.0.0
    #   if: always()
