name: Python tests

on: [pull_request]
jobs:
  python_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: OpenSearch instance and test with pytest
        # Build OpenSearch instance, wait 120 sec for port 9200, run pytest
        run: |
          make docker-run-opensearch &
          timeout 120 sh -c 'until nc -z $0 $1; do sleep 10; done' localhost 9200
          docker-compose run dev-env pytest
